export const blogposts = [{
    id: 0,
    title: 'Tailwind CSS is so intuitive that if you know CSS, you know Tailwind',
    content: "<img src='https://miro.medium.com/v2/resize:fit:1400/1*__f27S-qQF2CAASt5bOwqg.png'/><br>Styling CSS is fun and all but the job quickly becomes very tedious and annoying to maintain once the project grows bigger and bigger. At least that's what I experience building some websites using vanilla css. The problem with the traditional approach of CSS is sometimes the HTML and the CSS are too separated that it feels like a jenga game whenever we move, edit, or delete some line of CSS because how it might break your style somewhere else. In short, it's a mess.<br><br>The reason above is what makes me interested in dipping my toes into the world of Tailwind CSS, my intention at first is just to try thing out but once I finished my first mini project with it, I can't see myself using vanilla CSS again, especially on a component based project like React JS or laravel blade templating. The most surprising thing that I learned when trying out Tailwind is how well thought out everything is, everything is so intuitive that it basically like writing a regular CSS except it's not separated from your HTML and you wrote a lot less code.<br><br>The best advice I've got about learning Tailwind is not to be bother with tutorial or course about tailwind and just jump straight into project after skimming the official documentation. The tailwind team really done an amazing job translating CSS into their own inline style that very minimalist but very clearly thought out too. It makes learning tailwind the most fun I've experienced on my journey of learning web development.<br><br>If you're working with CSS and up to learning new things, I implore you to try Tailwind CSS.<br>",
    date: "2 February 2024",
    slug: "post-0"
  },{
    id: 1,
    title: "This is a merely placeholder post, don't click it!",
    content: "Welcome to The Placeholder Blog, where we're fully aware that this article is just a stand-in for something more meaningful. We promise you won't find any groundbreaking insights, life-changing advice, or profound revelations here. Instead, consider this a meta-experience in placeholder content – the blog post equivalent of elevator music.Consider this paragraph a canvas, waiting for the strokes of brilliance that will inevitably replace it. Picture a landscape of possibility, an empty space yearning for the weight of significance – a blank page, not as a canvas for creation, but as a placeholder for what's yet to come.<br><br>As you continue reading, or perhaps skimming, through these sentences, remember that you're not missing out on any groundbreaking insights or revolutionary ideas. There's no need to take notes or bookmark this page, for this is a transient moment in the blogosphere – a fleeting blip in the vast sea of online content. Maybe you're wondering why you're still reading. Is it curiosity? A sense of obligation to see if this placeholder truly lives up to its self-aware promise? Or perhaps it's just the sheer novelty of engaging with content that admits it's not aiming for greatness.<br><br>As we reach the end of this deliberately nondescript journey, we want to thank you for being a part of The Placeholder Chronicles. Your willingness to spend time with an article that acknowledges its own lack of substance is both commendable and slightly perplexing. Until our next rendezvous in the blogosphere, where meaningful content may take its place, embrace the transience, revel in the void, and appreciate the placeholder for what it is – a momentary pause in the cacophony of online chatter.<br>",
    date: "28 January 2024",
    slug: "post-1"
  },{
    id: 2,
    title: "This is a merely placeholder post, don't click it!",
    content: "<img src='../img/bed-1.jpg'/><br>Welcome to The Placeholder Blog, where we're fully aware that this article is just a stand-in for something more meaningful. We promise you won't find any groundbreaking insights, life-changing advice, or profound revelations here. Instead, consider this a meta-experience in placeholder content – the blog post equivalent of elevator music.Consider this paragraph a canvas, waiting for the strokes of brilliance that will inevitably replace it. Picture a landscape of possibility, an empty space yearning for the weight of significance – a blank page, not as a canvas for creation, but as a placeholder for what's yet to come.<br><br>As you continue reading, or perhaps skimming, through these sentences, remember that you're not missing out on any groundbreaking insights or revolutionary ideas. There's no need to take notes or bookmark this page, for this is a transient moment in the blogosphere – a fleeting blip in the vast sea of online content. Maybe you're wondering why you're still reading. Is it curiosity? A sense of obligation to see if this placeholder truly lives up to its self-aware promise? Or perhaps it's just the sheer novelty of engaging with content that admits it's not aiming for greatness.<br><br>As we reach the end of this deliberately nondescript journey, we want to thank you for being a part of The Placeholder Chronicles. Your willingness to spend time with an article that acknowledges its own lack of substance is both commendable and slightly perplexing. Until our next rendezvous in the blogosphere, where meaningful content may take its place, embrace the transience, revel in the void, and appreciate the placeholder for what it is – a momentary pause in the cacophony of online chatter.<br><br><img src='../img/bed-1.jpg'/>",
    date: "28 January 2024",
    slug: "post-2"
  }]  