export const blogposts = [{
    id: 0,
    title: 'Tailwind CSS is so intuitive that if you know CSS, you know Tailwind',
    content: "Welcome to The Placeholder Blog, where we're fully aware that this article is just a stand-in for something more meaningful. We promise you won't find any groundbreaking insights, life-changing advice, or profound revelations here. Instead, consider this a meta-experience in placeholder content – the blog post equivalent of elevator music.Consider this paragraph a canvas, waiting for the strokes of brilliance that will inevitably replace it. Picture a landscape of possibility, an empty space yearning for the weight of significance – a blank page, not as a canvas for creation, but as a placeholder for what's yet to come.<br><br>As you continue reading, or perhaps skimming, through these sentences, remember that you're not missing out on any groundbreaking insights or revolutionary ideas. There's no need to take notes or bookmark this page, for this is a transient moment in the blogosphere – a fleeting blip in the vast sea of online content. Maybe you're wondering why you're still reading. Is it curiosity? A sense of obligation to see if this placeholder truly lives up to its self-aware promise? Or perhaps it's just the sheer novelty of engaging with content that admits it's not aiming for greatness.<br><br>As we reach the end of this deliberately nondescript journey, we want to thank you for being a part of The Placeholder Chronicles. Your willingness to spend time with an article that acknowledges its own lack of substance is both commendable and slightly perplexing. Until our next rendezvous in the blogosphere, where meaningful content may take its place, embrace the transience, revel in the void, and appreciate the placeholder for what it is – a momentary pause in the cacophony of online chatter.<br>",
    date: "2 February 2024",
    slug: "post-0"
  },{
    id: 1,
    title: "This is a merely placeholder post, don't click it!",
    content: "Welcome to The Placeholder Blog, where we're fully aware that this article is just a stand-in for something more meaningful. We promise you won't find any groundbreaking insights, life-changing advice, or profound revelations here. Instead, consider this a meta-experience in placeholder content – the blog post equivalent of elevator music.Consider this paragraph a canvas, waiting for the strokes of brilliance that will inevitably replace it. Picture a landscape of possibility, an empty space yearning for the weight of significance – a blank page, not as a canvas for creation, but as a placeholder for what's yet to come.<br><br>As you continue reading, or perhaps skimming, through these sentences, remember that you're not missing out on any groundbreaking insights or revolutionary ideas. There's no need to take notes or bookmark this page, for this is a transient moment in the blogosphere – a fleeting blip in the vast sea of online content. Maybe you're wondering why you're still reading. Is it curiosity? A sense of obligation to see if this placeholder truly lives up to its self-aware promise? Or perhaps it's just the sheer novelty of engaging with content that admits it's not aiming for greatness.<br><br>As we reach the end of this deliberately nondescript journey, we want to thank you for being a part of The Placeholder Chronicles. Your willingness to spend time with an article that acknowledges its own lack of substance is both commendable and slightly perplexing. Until our next rendezvous in the blogosphere, where meaningful content may take its place, embrace the transience, revel in the void, and appreciate the placeholder for what it is – a momentary pause in the cacophony of online chatter.<br>",
    date: "28 January 2024",
    slug: "post-1"
  },{
    id: 2,
    title: "This is a merely placeholder post, don't click it!",
    content: "<img src='../img/bed-1.jpg'/><br>Welcome to The Placeholder Blog, where we're fully aware that this article is just a stand-in for something more meaningful. We promise you won't find any groundbreaking insights, life-changing advice, or profound revelations here. Instead, consider this a meta-experience in placeholder content – the blog post equivalent of elevator music.Consider this paragraph a canvas, waiting for the strokes of brilliance that will inevitably replace it. Picture a landscape of possibility, an empty space yearning for the weight of significance – a blank page, not as a canvas for creation, but as a placeholder for what's yet to come.<br><br>As you continue reading, or perhaps skimming, through these sentences, remember that you're not missing out on any groundbreaking insights or revolutionary ideas. There's no need to take notes or bookmark this page, for this is a transient moment in the blogosphere – a fleeting blip in the vast sea of online content. Maybe you're wondering why you're still reading. Is it curiosity? A sense of obligation to see if this placeholder truly lives up to its self-aware promise? Or perhaps it's just the sheer novelty of engaging with content that admits it's not aiming for greatness.<br><br>As we reach the end of this deliberately nondescript journey, we want to thank you for being a part of The Placeholder Chronicles. Your willingness to spend time with an article that acknowledges its own lack of substance is both commendable and slightly perplexing. Until our next rendezvous in the blogosphere, where meaningful content may take its place, embrace the transience, revel in the void, and appreciate the placeholder for what it is – a momentary pause in the cacophony of online chatter.<br><br><img src='../img/bed-1.jpg'/>",
    date: "28 January 2024",
    slug: "post-2"
  }]  